### ISSUE TITLE
`bazelisk version` displays commit hash as version string for releases after `v1.1.0`

### ISSUE THREAD

**Issue by karlding** [bazelbuild/bazelisk#112]
The `bazelisk` binaries on the releases page now seem to display the commit hash (instead of the tag name) whenever `bazelisk version` is run.

```bash
# Download v1.1.0
wget https://github.com/bazelbuild/bazelisk/releases/download/v1.1.0/bazelisk-linux-amd64 -O bazelisk-linux-amd64-v1.1.0

# Download v1.2.0
wget https://github.com/bazelbuild/bazelisk/releases/download/v1.2.0/bazelisk-linux-amd64 -O bazelisk-linux-amd64-v1.2.0

# Download v1.2.1
wget https://github.com/bazelbuild/bazelisk/releases/download/v1.2.1/bazelisk-linux-amd64 -O bazelisk-linux-amd64-v1.2.1

# Set execute permission
chmod +x bazelisk-linux-amd64-v1.*

# Check versions
./bazelisk-linux-amd64-v1.1.0 version --gnu_format
# Bazelisk v1.1.0
# bazel 2.0.0

./bazelisk-linux-amd64-v1.2.0 version --gnu_format
# Bazelisk 0830538ecc80bc874af3ba14b3c7bc9eab57ee63
# bazel 2.0.0

./bazelisk-linux-amd64-v1.2.1 version --gnu_format
# Bazelisk 56a03d98104be7cfa57d4bbdc03b4c7cea29a6c9
# bazel 2.0.0

# Check commit hashes
git show-ref --tags | grep -E 'v1.[1,2].[0,1]'
# fd66bc39dffe62c73db5edabd6d872d54ae88bd3 refs/tags/v1.1.0
# 0830538ecc80bc874af3ba14b3c7bc9eab57ee63 refs/tags/v1.2.0
# 56a03d98104be7cfa57d4bbdc03b4c7cea29a6c9 refs/tags/v1.2.1
```

I expected this to output the following:

```bash
./bazelisk-linux-amd64-v1.2.0 version --gnu_format
# Bazelisk v1.2.0
# bazel 2.0.0

./bazelisk-linux-amd64-v1.2.1 version --gnu_format
# Bazelisk v1.2.1
# bazel 2.0.0
```

Is this change expected?

**Comment by philwo** [comment]
Hi @karlding,

sorry, this happened by mistake. I will push out a new release soon that will print its correct version number again.

@fweikert When you build a release, please make sure to build it from the tag on a trusted Google machine using the `build.sh` script and then give it a final, manual test to check that the binaries work and print the correct version. FYI I'm not using the release pipeline on Buildkite that we created some time ago, so maybe that one doesn't work or is buggy, in case you were using that.

**Comment by fweikert** [comment]
If that's the case we should fix the release pipeline and add a small shell test that ensures no future instances of this bug can happen.

**Comment by philwo** [comment]
But.. we can also just run `build.sh` and check that the resulting binary can print its version, right? No test, no release pipeline, no complexity - pure win.

**Comment by philwo** [comment]
The latest release 1.3.0 correctly prints its version string again.

I updated our build script to make it easy to spot any mistake in the future: https://github.com/bazelbuild/bazelisk/commit/4b1375bdada94be345679335a4c32cf179f07711.
