### ISSUE TITLE
Provide package for chocolatey

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazelisk#128]
Bazel is already available for chocolatey and it would be really practical if bazelisk would also be available in the package manager.
This makes it easy to have it in ci systems without the need to use go or python.

**Comment by UebelAndre** [comment]
I missed this when I opened #161 I think this work is almost done

**Comment by limdor** [comment]
@UebelAndre from my side this could be closed. I already started using it. https://github.com/limdor/bazel-examples/blob/master/.appveyor.yml#L31
Thanks!

**Comment by UebelAndre** [comment]
Don't thank me, thank @digitalcoyote for he's the real hero! 😄

**Comment by UebelAndre** [comment]
@limdor I think you should close the issue if it's resolved for you 😄

**Comment by limdor** [comment]
Sorry, I did not see that I could close myself, done.
