### ISSUE TITLE
How to uninstall bazelisk?

### ISSUE THREAD

**Issue by MikhailTymchukFT** [bazelbuild/bazelisk#144]
I installed the bazelisk with a binary (MacOS): https://github.com/bazelbuild/bazelisk/releases/download/v1.5.0/bazelisk-darwin-amd64
How do I uninstall it?

**Comment by philwo** [comment]
You can just delete the downloaded Bazelisk executable.

To further clean up, you can delete Bazelisk's cache folder: `$HOME/Library/Caches/Bazelisk`. To see it in Finder, press Cmd-Shift-G and enter `~/Library/Caches` in the dialog. Then you should see the Bazelisk folder there, which you can just delete. :)

Hope this helps!

**Comment by MikhailTymchukFT** [comment]
But the bazel file inside `/usr/local/bin/bazel` is a symlink to a wrapper from bazelisk, should I remove it too?

```
$ ls -la /usr/local/bin | grep bazel
lrwxr-xr-x    1 mikhailtymchuk  admin        30 Apr 23 18:10 bazel -> /usr/local/lib/bazel/bin/bazel
```
