### ISSUE TITLE
Please add freebsd support. Bazel works fine when installed using the package manager.

### ISSUE THREAD

**Issue by yesudeep** [bazelbuild/bazelisk#150]
Hi!

I get this when running bazelisk on GhostBSD 20.08.04

```shell
2020/08/15 17:29:49 could not download Bazel: could not determine filename to use for Bazel binar: unsupported operating system "freebsd", must be Linux, macOS or Windows
```

Could you please add support for FreeBSD as well?

**Comment by yesudeep** [comment]
Actually, having tried to build multiple libraries on FreeBSD/OpenBSD, I'd highly recommend adding support for them because it's helped me catch several subtle errors that occur on those systems. Bazel support for these OS's would allow packages to adopt Bazel as a build system faster too.

**Comment by rajhlinux** [comment]
> Actually, having tried to build multiple libraries on FreeBSD/OpenBSD, I'd highly recommend adding support for them because it's helped me catch several subtle errors that occur on those systems. Bazel support for these OS's would allow packages to adopt Bazel as a build system faster too and would make porting software easier.

How did you install bazel on freebsd?

**Comment by hukl** [comment]
+ 1 for FreeBSD support - can't get libtensorflow to run without it :/

**Comment by fweikert** [comment]
I'm closing this issue since we cannot do anything here before Bazel publishes binaries for FreeBSD (which seems unlikely in the near future).
