### ISSUE TITLE
Bazelisk 1.6.1: Error: exec: 'patch' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by marleypowell** [bazelbuild/bazelisk#153]
I am running the patch command in a js script. This works fine on linux but on windows I get this error:
```
'patch' is not recognized as an internal or external command,
operable program or batch file.
Error: exec: 'patch' is not recognized as an internal or external command,
operable program or batch file.
```
This might be related to this bug fix for windows release https://github.com/bazelbuild/bazelisk/releases/tag/v1.6.1.
The patch command works fine when using bazelisk 1.5.0 on windows.

**Comment by philwo** [comment]
@marleypowell Can you confirm that this happens with Bazelisk 1.6.1? 1.6.0 had the bug, but 1.6.1 should have the fix.

@coeuvre FYI

**Comment by marleypowell** [comment]
> @marleypowell Can you confirm that this happens with Bazelisk 1.6.1? 1.6.0 had the bug, but 1.6.1 should have the fix.
> 
> @coeuvre FYI

Yeah I tested on 1.6.1 and 1.6.0 and I had errors on both versions.

**Comment by coeuvre** [comment]
Can you provide a minimal example that can reproduce the bug? Thanks!

**Comment by marleypowell** [comment]
@coeuvre

package.json
```
{
    "scripts": {
        "postinstall": "node apply-patches.js",
    },
}
```

apply-patches.js
```
shelljs.cat("patchFile").exec('patch -p0');
```

WORKSPACE.bazel
```
yarn_install(
    name = "npm",
    data = ["//:apply-patches.js"],
    package_json = "//:package.json",
    symlink_node_modules = False,
    yarn_lock = "//:yarn.lock",
)
```

When I run the `bazelisk build` command it fails during the `yarn_install` step when it executes the `postinstall` script...

**Comment by coeuvre** [comment]
Sorry, I can't reproduce the bug. I am using the repo https://github.com/coeuvre/bazelisk-issue-153 which is basically the steps above and no error shows after running `bazelisk query @npm//...`.

Can you confirm that you can run `node apply-patches.js` directly without error?

**Comment by marleypowell** [comment]
> Sorry, I can't reproduce the bug. I am using the repo https://github.com/coeuvre/bazelisk-issue-153 which is basically the steps above and no error shows after running `bazelisk query @npm//...`.
> 
> 
> 
> Can you confirm that you can run `node apply-patches.js` directly without error?

I can confirm that I can run `node apply-patches.js` without error.

**Comment by coeuvre** [comment]
Thanks for confirming that. Can you also give a try to reproduce using the repo I mentioned above? I am not sure whether I was missing something in that repo.

**Comment by marleypowell** [comment]
Hi after running your example repo then retrying with `bazelisk@1.6.1` it appears to now be working. I think it must have been something to do with my local setup. Multiple restarts might have been the solution to my problem... 

Thank you for taking the time to try and help!
