### ISSUE TITLE
Bazelisk for arm64

### ISSUE THREAD

**Issue by rmohr** [bazelbuild/bazelisk#154]
Hi,

Bazel recently started to release arm64 builds. Would it make sense to cross-compile bazelisk and release it for arm64 too?

**Comment by philwo** [comment]
We have Linux arm64 binaries since Bazelisk 1.6.0 in the releases:

<img width="317" alt="Screenshot 2020-08-28 at 17 07 21" src="https://user-images.githubusercontent.com/504652/91583081-fa0c7f80-e950-11ea-8cd8-aea8f583fa61.png">

Is there something else missing?

**Comment by rmohr** [comment]
Oh my god :D Thanks for pointing that out!
