### ISSUE TITLE
Cleanup: volatile-status

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazelisk#155]
I'm fixing rules_nodejs right now to let you pick arbitrary status keys in the stamping implementation - then we can remove this change to stamp.sh which was a workaround https://github.com/bazelbuild/bazelisk/commit/541325d070f320e78c2e30d1d6feeaba787c8162#diff-9004e026c175cbe67e8119d1bc0fc801

**Comment by philwo** [comment]
Nice, thank you!
