### ISSUE TITLE
Request: Publish Chocolatey Package

### ISSUE THREAD

**Issue by UebelAndre** [bazelbuild/bazelisk#161]
Would it be possible to publish releases of this to [chocolatey](https://chocolatey.org/)? 

https://chocolatey.org/packages?q=bazelisk

**Comment by digitalcoyote** [comment]
I'd be willing to create/maintain a package. I have an AU repo that would watch this repository's releases and automatically pack/publish for chocolatey.

Is that executable an installer?

**Comment by UebelAndre** [comment]
The `.exe` in the releases page is an executable, as far as I can recall (not on my windows machine right now).

**Comment by digitalcoyote** [comment]
I got a package together, but it flagged the malware scanners when I was testing it. Chocolatey won't approve any packages that don't pass their malware scans. If someone wants to try to publish it anyway, I have the update/install and nuspec files pretty much ready for an AU repo. I'm going to do some more testing to make sure I'm pulling the file I think I am.

**Comment by UebelAndre** [comment]
Can you make a new issue containing the logs of the scan once you have some confidence that the issue is in `bazelisk`?

**Comment by digitalcoyote** [comment]
Virus total came back without a single hit on the release url. Im going to scan my VM. Something seems like it's not right.

**Comment by digitalcoyote** [comment]
For anyone else reading this, if you review the results, it basically says the bazelisk behaves exactly like it's supposed to.

 If I can't get it to pass the scanners, I may try talking to chocolatey reviewers to see if they'd make an exception based on that report.

**Comment by UebelAndre** [comment]
Seems related to #165 btw

**Comment by digitalcoyote** [comment]
Got word back, they said to include a note about it in the description so the reviewer can check it out. They said users can use that to decide if they want to install it or not. 

https://chocolatey.org/packages/bazelisk

**Comment by UebelAndre** [comment]
Maybe with #168 closed the chocolatey package won't have this issue either?

**Comment by digitalcoyote** [comment]
I'll double check it, but I'm guessing it won't have an issue.

**Comment by UebelAndre** [comment]
Any updates on the published package? Will it work by simply running `choco install bazelisk` if the security exception has been fixed?

**Comment by digitalcoyote** [comment]
It's approved.

When they approved it, it immediately queued up the next version and I
didn't notice it had been approved.

**Comment by UebelAndre** [comment]
Awesome! Thanks for doing that @digitalcoyote!!! 🎉 🙏 🎉 

Greatly appreciated 😄
