### ISSUE TITLE
Clarifications about bazel installation 

### ISSUE THREAD

**Issue by lucio-cyber** [bazelbuild/bazelisk#167]
Hi, 
I would like to have some clarification on how to install bazel automatically.
Just run from the shell: “/user/local/bin/.bazelversion” and after “./bazelisk build //.bazelversion”? Or just the second command is enough?

What happens to the CPU and RAM?
Does it take up a lot?
Best Regards,
Lucio

**Comment by philwo** [comment]
Hi @lucio-cyber,

to use Bazelisk, download the correct binary for your operating system and CPU architecture. For example, for a Mac, you'd use `bazelisk-darwin-amd64`, for Linux amd64 you'd use `bazelisk-linux-amd64`:

Example for Linux:

```
$ curl -Lo /usr/local/bin/bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64
$ chmod +x /usr/local/bin/bazelisk
```

Now you can just run Bazelisk and it will always automatically give you the latest stable Bazel version:

```
$ bazelisk version
Bazelisk version: 1.6.1
Build label: 3.5.0
...
$ bazelisk build //my:target
...
```

If you want your project to always use e.g. Bazel 3.4.1, you can put a `.bazelversion` file into its root directory (next to the `WORKSPACE` file:

```
$ cd ~/src/myproject
$ echo 3.4.1 > .bazelversion
$ bazelisk version
Bazelisk version: 1.6.1
Build label: 3.5.0
...
$ bazelisk build //my:target
```

The CPU and RAM usage of Bazelisk itself is negligible, as it is just a little wrapper for Bazel.

Bazel itself uses a lot more. 😊

Hope this helps!

**Comment by lucio-cyber** [comment]
Hi @philwo, thank you so much for helping me.
Best Regards

**Comment by Pyrestone** [comment]
> to use Bazelisk, download the correct binary for your operating system and CPU architecture. For example, for a Mac, you'd use `bazelisk-darwin-amd64`, for Linux amd64 you'd use `bazelisk-linux-amd64`:
> 
> Example for Linux:
> 
> ```
> $ curl -Lo /usr/local/bin/bazelisk https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64
> $ chmod +x /usr/local/bin/bazelisk
> ```

This should really be in the main README.md of the repo.
