### ISSUE TITLE
Windows detects the exe as a trojan virus

### ISSUE THREAD

**Issue by abstractgears** [bazelbuild/bazelisk#168]
Windows Defender detects the release exe as Trojan:Win32/Ymacco.AAEE 

(I know how to override this, but it will be nice if the release is fixed)

**Comment by philwo** [comment]
Hi @abstractgears,

sorry for the trouble! I investigated what causes this here: https://github.com/bazelbuild/bazelisk/issues/97#issuecomment-696212008

I'll release a new version soon that will hopefully not be flagged by the virus scanners.

**Comment by UebelAndre** [comment]
Has this been resolved?

**Comment by philwo** [comment]
@UebelAndre I'll try tomorrow on my Windows machine whether Windows Defender complains and will report back.

**Comment by abstractgears** [comment]
@UebelAndre , The issue is resolved when I tried v1.7.1, Thanks

**Comment by abstractgears** [comment]
Closing issue, since in version v1.7.1 the windows defender stopped complaining for me
