### ISSUE TITLE
Support GitHub API Token

### ISSUE THREAD

**Issue by dflems** [bazelbuild/bazelisk#18]
If you're on a shared network, you can sometimes see messages like this from the API:

```
$ curl https://api.github.com/repos/bazelbuild/bazel/releases
{
  "message": "API rate limit exceeded for 123.45.67.89. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
  "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

Homebrew (for instance) has support for supplying a token via `HOMEBREW_GITHUB_API_TOKEN`, making it more likely that the API request won't get rate limited. It would be nice for `bazelisk` to support this as well, perhaps via a similar convention (`BAZELISK_GITHUB_API_TOKEN`) to perform authenticated requests instead.

**Comment by dflems** [comment]
Ah I just noticed bazelisk _only_ pulls the releases list from `github.com` and nothing else. Maybe it would be easier to publish something like `https://releases.bazel.build/latest-version.txt` on your end and pull that down instead :)

**Comment by keith** [comment]
@philwo any ideas on a solution for this? I could dedicate some time to this if we had a clear path

**Comment by philwo** [comment]
Both ideas sound good - using a GitHub token (if available) and storing that information on our own host. I can handle the latter part, but integrating it into our release pipeline will take some time.

@keith do you want to look into using a GitHub token? Sounds like a good and quick fix for this. I'm not sure where people would usually store these tokens - environment variable? If that's the usual way, sure, why not. :)

**Comment by keith** [comment]
I've submitted an attempt at this here https://github.com/bazelbuild/bazelisk/pull/62
