### ISSUE TITLE
Cannot find bazel. Please install bazel.

### ISSUE THREAD

**Issue by cement-head** [bazelbuild/bazelisk#202]
Used bazelisk to install bazel.

Trying to install TensorFlow.

```
$ ./configure 
Cannot find bazel. Please install bazel.
```
But I have bazel installed;

`$ bazelisk                                                       [bazel release 3.1.0]`

Please help.

**Comment by philwo** [comment]
Hi @cement-head,

Bazelisk is a wrapper for Bazel, not a separate installer. Can you install Bazelisk as your `bazel` command on the PATH? That should make it work. :)

Cheers,
Philipp

**Comment by nicolaspi** [comment]
Had the same issue, solved it with:
``` 
$ ln -s $(go env GOPATH)/bin/bazelisk $(go env GOPATH)/bin/bazel
```

**Comment by cement-head** [comment]
I ended up downloading and installing the pre-built binaries from nVIDIA.
