### ISSUE TITLE
Building bazelisk requires Go 1.12 but in the Readme says 1.11

### ISSUE THREAD

**Issue by limdor** [bazelbuild/bazelisk#206]
This commit use ReplaceAll that is only available in Go 1.12
https://github.com/bazelbuild/bazelisk/commit/3b5aa4468260727974ea62d4e9e810a17649f5b7
However in the Readme file is mentioned that it is required Go 1.11
https://github.com/bazelbuild/bazelisk#requirements

The readme should be updated or the code should be change to be compatible with Go 1.11.
In case that the first option is decided, keep in mind that there are several linux distributions that come with a Go 1.11 and can make CI more complicated.
https://packages.debian.org/buster/golang

**Comment by fweikert** [comment]
Bazelisk@head and release v1.7.5 should be compatible with Go 1.11 again

**Comment by fweikert** [comment]
Filed https://github.com/bazelbuild/bazelisk/issues/216 for future work.
