### ISSUE TITLE
darwin_arm64 is an invalid combination for bazelisk.js

### ISSUE THREAD

**Issue by jakehz** [bazelbuild/bazelisk#212]
I ran into an error while trying to build with bazelisk, and it seems like the problem is that, since I am on an M1 macbook pro, my architecture was detected as "darwin_arm64". The darwin_amd64 executable seems to run fine. Perhaps bazelisk.js should run this instead until m1 support is here?
![image](https://user-images.githubusercontent.com/11205936/106426903-43d72580-641b-11eb-9feb-1c08c80b9af4.png)

**Comment by philwo** [comment]
I just made the necessary changes to build a native Apple Silicon version Bazelisk, so the release that I'm about to create should fix this. 😊 

Context: https://github.com/bazelbuild/bazelisk/pull/242
