### ISSUE TITLE
Conduct new Bazelisk release to be compatible with latest Bazel release (4.x)

### ISSUE THREAD

**Issue by davido** [bazelbuild/bazelisk#213]
The latest available Bazelisk release is 1.7.4.

Gerrit Code Review is trying to upgrade Bazel version used on the CI, but it's failing to do so, because the most recent Bazelisk release avaiable: 1.7.4 is not compatible with Bazel 4.0.0, because `rules_nodejs` library is outdated and suffers from invalid escape sequences in its Starlark code:

```
  $ bazel version
  Build label: 4.0.0

  $ git checkout v1.7.4
  HEAD is now at 3b5aa44 Discard releases when reading candidates (#190)

  $ rm .bazelversion
  
  $ bazel build --config=release //:bazelisk
ERROR: /home/davido/.cache/bazel/_bazel_davido/aff24bce8409e49e2caac8d88df762ad/external/build_bazel_rules_nodejs/internal/node/node.bzl:89:45: invalid escape sequence: \/. You can enable unknown escape sequences by passing the flag --incompatible_restrict_string_escapes=false
ERROR: /home/davido/.cache/bazel/_bazel_davido/aff24bce8409e49e2caac8d88df762ad/external/build_bazel_rules_nodejs/internal/node/node.bzl:89:64: invalid escape sequence: \.. You can enable unknown escape sequences by passing the flag --incompatible_restrict_string_escapes=false
ERROR: error loading package '': in /home/davido/.cache/bazel/_bazel_davido/aff24bce8409e49e2caac8d88df762ad/external/build_bazel_rules_nodejs/index.bzl: Extension 'internal/node/node.bzl' has errors
INFO: Elapsed time: 0.579s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```

Known workaround would be to un-flip the option: `--incompatible_restrict_string_escapes=false`, but it's discouraged by Bazel team:

```
  $ bazel build --config=release --incompatible_restrict_string_escapes=false //:bazelisk
INFO: Analyzed target //:bazelisk (45 packages loaded, 6968 targets configured).
INFO: Found 1 target...
Target //:bazelisk up-to-date:
  bazel-bin/bazelisk_/bazelisk
INFO: Elapsed time: 22.559s, Critical Path: 1.19s
INFO: 2 processes: 1 internal, 1 linux-sandbox.
INFO: Build completed successfully, 2 total actions
```

Releasing from Bazelisk@HEAD would fix the problem, because the `rules_nodejs` was fixed in: 8ac77f1b.

FTR: Here is the Bazel update attempt in gerrit project: [1].

//CC @alexeagle @philwo 

[1] https://gerrit-review.googlesource.com/c/gerrit-ci-scripts/+/296132

**Comment by alexeagle** [comment]
I'm confused, bazelisk gives you any version of Bazel including 4.0.0. I think there's something else you need to upgrade?

**Comment by alexeagle** [comment]
Oh I see you are compiling bazelisk from source. Why do you do that?

**Comment by davido** [comment]
> Oh I see you are compiling bazelisk from source. Why do you do that?

I don't remember why we set up building Bazelisk build from source for our CI image. We could probably just download it from GH release page, e.g: **https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64**

**Comment by lucamilanesio** [comment]
> > Oh I see you are compiling bazelisk from source. Why do you do that?
> 
> I don't remember why we set up building Bazelisk build from source for our CI image. We could probably just download it from GH release page, e.g: **https://github.com/bazelbuild/bazelisk/releases/download/v1.7.4/bazelisk-linux-amd64**

Let me check on the history and the associated review.

**Comment by davido** [comment]
Unrelated here, but it would be great to have Debian package for Bzelisk.

This is how we install Bazel iteself on the CI docker image:

```
# Install Bazel
  RUN apt-get update && \
    wget -O /tmp/bazel_${BAZEL_VER}-linux-x86_64.deb https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VER}/bazel_${BAZEL_VER}-linux-x86_64.deb && \
    (dpkg -i /tmp/bazel_${BAZEL_VER}-linux-x86_64.deb; apt-get install -f -y) && \
    rm /tmp/bazel_${BAZEL_VER}-linux-x86_64.deb && \
    bash -c 'bazel version'
```

**Comment by philwo** [comment]
I just built Bazelisk successfully with Bazel 4.1.0, so I assume this is fixed?

**Comment by davido** [comment]
Right!
