### ISSUE TITLE
Windows detects trojan in bazelisk 

### ISSUE THREAD

**Issue by wcwelcha** [bazelbuild/bazelisk#217]
Report from Windows Security:
> Trojan:Win32/Fuerboos.B!cl
Alert level: Severe
Status: Active
Date: 2/23/2021 10.19 AM
Category: Trojan
Details: This program is dangerous and executes commands from an attacker.
Affected items:
    file: C:\bin\npm\node_modules\@bazel\bazelisk\bazelisk-windows_amd64.exe

Install log:
> C:\Users\wcwelch\Documents\dev>npm install --verbose -g @bazel/bazelisk
npm info it worked if it ends with ok
npm verb cli [
npm verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'install',
npm verb cli   '--verbose',
npm verb cli   '-g',
npm verb cli   '@bazel/bazelisk'
npm verb cli ]
npm info using npm@6.14.11
npm info using node@v14.16.0
npm verb npm-session 0cfdbd29d2710b84
npm http fetch GET 304 http://registry.npmjs.org/@bazel%2fbazelisk 201ms (from cache)
npm timing stage:loadCurrentTree Completed in 227ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 1ms
npm timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 3ms
npm timing stage:loadIdealTree Completed in 8ms
npm timing stage:generateActionsToTake Completed in 2ms
npm verb correctMkdir C:\Users\wcwelch\AppData\Roaming\npm-cache\_locks correctMkdir not in flight; initializing
npm verb makeCacheDir UID & GID are irrelevant on win32
npm verb lock using C:\Users\wcwelch\AppData\Roaming\npm-cache\_locks\staging-12d74307617c30d8.lock for c:\bin\npm\node_modules\.staging
npm timing action:extract Completed in 231ms
npm timing action:finalize Completed in 47ms
npm timing action:refresh-package-json Completed in 16ms
npm info lifecycle @bazel/bazelisk@1.7.5\~preinstall: @bazel/bazelisk@1.7.5
npm timing action:preinstall Completed in 2ms
npm info linkStuff @bazel/bazelisk@1.7.5
npm verb linkBins [
npm verb linkBins   { bazelisk: 'bazelisk.js', bazel: 'bazelisk.js' },
npm verb linkBins   'c:\\bin\\npm',
npm verb linkBins   true
npm verb linkBins ]
c:\bin\npm\bazelisk -> c:\bin\npm\node_modules\@bazel\bazelisk\bazelisk.js
c:\bin\npm\bazel -> c:\bin\npm\node_modules\@bazel\bazelisk\bazelisk.js
npm timing action:build Completed in 14ms
npm info lifecycle @bazel/bazelisk@1.7.5\~install: @bazel/bazelisk@1.7.5
npm timing action:install Completed in 2ms
npm info lifecycle @bazel/bazelisk@1.7.5\~postinstall: @bazel/bazelisk@1.7.5
npm timing action:postinstall Completed in 1ms
npm verb unlock done using C:\Users\wcwelch\AppData\Roaming\npm-cache\_locks\staging-12d74307617c30d8.lock for c:\bin\npm\node_modules\.staging
npm timing stage:executeActions Completed in 343ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 597ms
\+ @bazel/bazelisk@1.7.5
added 1 package in 0.6s
npm verb exit [ 0, true ]
npm timing npm Completed in 937ms
npm info ok

**Comment by philwo** [comment]
Hey @wcwelcha,

sorry for the trouble 😞  We had a false positive like this before in https://github.com/bazelbuild/bazelisk/issues/168 and https://github.com/bazelbuild/bazelisk/issues/97#issuecomment-696212008.

I currently cannot reproduce this on VirusTotal.com, which says the file is not detected as a virus by any scanner: https://www.virustotal.com/gui/file/3370b9064a5bee879b675a77359ca14b3d2c5fa06364ae16b9ab2ff1773c9d0f/detection

Could you please verify the SHA256 hash of the downloaded file to ensure you didn't get a malicious copy?

```
$ sha256sum bazelisk-windows-amd64.exe 
3370b9064a5bee879b675a77359ca14b3d2c5fa06364ae16b9ab2ff1773c9d0f  bazelisk-windows-amd64.exe
```

And also try to update your Windows Security signatures (I think using Windows Update should be fine)?

I will try to reproduce on my personal machine later.

Cheers,
Philipp

**Comment by wcwelcha** [comment]
Philipp,

Thanks for the quick response.
I actually verified the sha256 before filing the bug.

Also, this is running on a fresh Windows 10 Pro system; created and updated yesterday.

Thanks,
  Bill

**Comment by kadel** [comment]
I can confirm this. I'm having the same problem with v1.7.5.
```
Name: bazelisk-windows-amd64.exe
Size: 7276032 bytes (7105 KiB)
SHA256: 3370B9064A5BEE879B675A77359CA14B3D2C5FA06364AE16B9AB2FF1773C9D0F
```

But for me it gets detected as **Trojan:Win32/Glupteba!ml**

**Comment by philwo** [comment]
I can reproduce this on my personal Windows 10 machine, even with a freshly built Bazelisk binary.

I have reported this to Microsoft as a false-positive here via this form: https://www.microsoft.com/en-us/wdsi/filesubmission

Resulting URL (probably only visible to myself): https://www.microsoft.com/en-us/wdsi/submission/6514fc3b-5cf1-4e29-93cd-9595db629ecc

I will report back when I hear from them.

One idea I had was to build Bazelisk releases on Google's internal release building platform, which would probably allow us to use our code signing certificate. This is probably a good idea anyway and hopefully would avoid these false positives or at least make them less likely. 🤔

**Comment by philwo** [comment]
I received a reply from Microsoft:

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

That was quick! :)
