### ISSUE TITLE
Provide ARM releases (for Mac M1)

### ISSUE THREAD

**Issue by marcelloromani** [bazelbuild/bazelisk#219]
Wonder if it's possible to provide ARM releases for `bazelisk` just as there are for `bazel`.

**Comment by chrisdunelm** [comment]
+1 Would very much appreciate this. Would love to use bazelisk on a Raspberry Pi.

**Comment by mistic** [comment]
Can we also provide the darwin arm release for the new M1 chips ?

**Comment by marcelloromani** [comment]
@mistic That's exactly what this issue is about. I'll edit the description for clarity. Please give it a thumbs to help the issue get noticed.

**Comment by philwo** [comment]
My Apple Silicon MacBook Pro should hopefully arrive tomorrow, I’ll look into it then 😊

**Comment by philwo** [comment]
The new machine is so fast.. I can't help but just try various things and enjoy how snappy everything is 😅 The M1 is so nice.

Building a version of Bazelisk for darwin arm64 should be straight forward, the question is what do we do about Bazel versions that do not have a native Apple Silicon binary. Automatically fallback to the x86_64 version? Just error? What would you prefer?

I've asked @meteorcloudy to help me get the cherry-picks for Bazel 4.1.0 for Apple Silicon in, so if all goes well, this will be our first official release with native binaries and of course Bazelisk will be ready in time :)

**Comment by mistic** [comment]
@philwo thanks for looking into it! 

> what do we do about Bazel versions that do not have a native Apple Silicon binary. Automatically fallback to the x86_64 version? Just error? What would you prefer?

I would say the later. Just error and let the user know in order to use that version of bazel it needs to configure rosetta and run bazelisk and bazel through it. As of today the last published bazel version `4.0.0` hasn't published the darwin_arm64 artifacts but I believe in the next release it will already have those and then the whole integration will start to work together and make more sense, in my opinion ofc!

**Comment by alexeagle** [comment]
Ping on this one, as Bazel 4.1 is out today-ish, we'll need the bazelisk release as well

**Comment by philwo** [comment]
@alexeagle Thanks for pinging, I'll make sure that we get this ready in time for the 4.1.0 release.

Regarding that one... let me post an update on the release issue 🙄

**Comment by philwo** [comment]
I also sent a PR to Homebrew to add arm64 support, which has been merged now :)
