### ISSUE TITLE
could not resolve the version 'latest' to an actual version number

### ISSUE THREAD

**Issue by fuhailin** [bazelbuild/bazelisk#220]
I download the latest version bazelist for my Mac, but it show bazelist could get bazel from GCS bucket. Here is the error messgae , how should i resolve this?

`could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list Bazel versions in GCS bucket: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": net/http: TLS handshake timeout`

when I connect a gloable proxy, bazelist show following error message:
`could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list Bazel versions in GCS bucket: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: could not fetch https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/: Get "https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/": read tcp 192.168.43.5:57885->172.217.24.10:443: read: connection reset by peer`

**Comment by philwo** [comment]
Hi,

it sounds like your network is not allowing access to https://www.googleapis.com/ (with or without proxy).

Unfortunately with the current Bazelisk version it is not possible to fallback to GitHub when GCS is not available. Apparently we implemented the reverse direction (https://github.com/bazelbuild/bazelisk/commit/46d319d70558aa39a3a178a95ff18fec47dc5083) but haven't considered that GCS might not be reachable.

I will have to think about how we could solve this in a simple way. Sorry that I can't offer you a quick workaround :/

Pinging @fweikert just in case he has an idea.

**Comment by fweikert** [comment]
Workaround:
1. In your terminal: navigate to your workspace root
2. Run `echo "BAZELISK_BASE_URL=https://github.com/bazelbuild/bazel/releases/download" > .bazeliskrc`

**Comment by philwo** [comment]
Nice, thank you Florian!

**Comment by Lr-2002** [comment]
> Workaround:
> 
> 1. In your terminal: navigate to your workspace root (= directory with the WORKSPACE file)
> 2. Run `echo "BAZELISK_BASE_URL=https://github.com/bazelbuild/bazel/releases/download" > .bazeliskrc`

Sorry ,It's seems the command don't work on my pc ,is there any other method to solve the problem?

**Comment by fweikert** [comment]
Are you running Windows? You can create the .bazeliskrc file manually in your workspace directory. Then open it and add the following line:

BAZELISK_BASE_URL=https://github.com/bazelbuild/bazel/releases/download

**Comment by huxiaoxiang** [comment]
> 2\. echo "BAZELISK_BASE_URL=https://github.com/bazelbuild/bazel/releases/download" > .bazeliskrc

what should I config if I install from .sh file?

**Comment by fweikert** [comment]
1. For each of your Bazel projects: find the directory that contains the WORKSPACE file
2. Create a file called .bazeliskrc with the following content:
`BAZELISK_BASE_URL=https://github.com/bazelbuild/bazel/releases/download`

**Comment by ninnyyan1993** [comment]
hi, @fweikert, I am working on ubuntu and facing the same error now, how could I solve this? thank you

**Comment by ninnyyan1993** [comment]
> 1. For each of your Bazel projects: find the directory that contains the WORKSPACE file
> 2. Create a file called .bazeliskrc in this directory, and write the following content:
>    `BAZELISK_BASE_URL=https://github.com/bazelbuild/bazel/releases/download`

BTW, I have already do this, but not works. running in docker.

**Comment by JisonRWang** [comment]
I use @keanedawg 's method ,and I finally succeed!!!
Like this
![d1abd0394be865019dd4ec73ab85988](https://user-images.githubusercontent.com/7278275/165897660-821080e1-ef9c-4064-8065-d803b3eda0ae.png)

**Comment by mark8s** [comment]
I also use @keanedawg 's method ,and I finally succeed!!!

**Comment by xwjahahahaha** [comment]
> 

it works, thx

**Comment by xwjahahahaha** [comment]
> I was having the same issues where setting the base url environment world didn't seem to work. It turned out the issue was indeed that googleapis.com was blocked from my company's network.
> 
> I set the BAZELISK_BASE_URL but that didn't work for whatever reason, so I ended up just explicitly setting the Bazel version in the `.bazeliskrc` rather than always getting the latest.
> 
> `echo "USE_BAZEL_VERSION=4.1.0" > .bazeliskrc`
> 
> The point is that the issue was that googleapis (which checks for latest version) is blocked, but the registry to download bazel was not. So just setting the version number worked for me.

it works, thx

**Comment by LiushuiXiaoxia** [comment]
```
# .zshrc
export USE_BAZEL_VERSION=5.4.0
export BAZELISK_BASE_URL=https://github.com/bazelbuild/bazel/releases/download
```

**Comment by 9527-csroad** [comment]
> 

Hi, I am running on windows and I have tried your suggestion. It doesnt work. I dont know how to fix it.

**Comment by 9527-csroad** [comment]
![image](https://user-images.githubusercontent.com/52602255/224521063-57017dfc-893c-4430-910d-1582f85872c1.png)
plz help me

**Comment by LiushuiXiaoxia** [comment]
我这边用的是mac，window没有试过呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bazelbuild/bazelisk"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月12日(星期天) 上午10:38
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bazelbuild/bazelisk] could not resolve the version 'latest' to an actual version number (#220)





 

 plz help me

**Comment by anniezfy** [comment]
> 

Thanks, I get succeed followed by your advice~
