### ISSUE TITLE
Fetch rolling releases from GCS

### ISSUE THREAD

**Issue by fweikert** [bazelbuild/bazelisk#228]
Bazelisk currently fetches rolling releases from GitHub. However, GCS generally has higher availability, so we should just download release binaries from GCS.

Note: This request is currently blocked by the fact that we don't actually publish rolling releases yet.

**Comment by davido** [comment]
Just noticed:

```
  $ cat .bazelversion
  5.0.0-pre.20210510.2rc1
```

Doesn't seem to work:

```
  $ bazelisk build gerrit
2021/06/02 13:03:32 could not resolve the version '5.0.0-pre.20210510.2rc1' to an actual version number: Invalid version '5.0.0-pre.20210510.2rc1'
```

**Comment by fweikert** [comment]
We currently don’t support release candidates of rolling releases. Right now there’s only a single rolling release, 5.0.0-pre.20210510.2.2, which will be fetched from GitHub (please make sure that you have the latest Bazelisk version).

Our release infra still has some rough edges when it comes to rolling releases - I want to polish it next week and also publish better documentation.

**Comment by davido** [comment]
Thanks for clarifying.

It worked with: `5.0.0-pre.20210510.2.2` with Bazelisk@HEAD.

**Comment by keith** [comment]
Here's a PR for this original issue https://github.com/bazelbuild/bazelisk/pull/319
