### ISSUE TITLE
Wildcard in bazelversion

### ISSUE THREAD

**Issue by AnakinMac** [bazelbuild/bazelisk#251]
I have a project with .bazelversion defined as 4.*.*, which works fine with bazel, but bazelisk complains about the wildcard 

2021/07/08 21:06:02 could not resolve the version '4.*.*' to an actual version number: Invalid version '4.*.*'

Is there any plan to support this?

Thanks

**Comment by limdor** [comment]
You can use x for the wildcard, for example 4.x
