### ISSUE TITLE
bazel nojdk version

### ISSUE THREAD

**Issue by tradergt** [bazelbuild/bazelisk#267]
We don't use java at all and would like to use the nojdk version of bazel. (less to download in our ci/cd jobs).

Is it possible to add support for it? Does it actually support it now and I just have not figured it out?

**Comment by linzhp** [comment]
Most of the Bazel's codebase is written in Java. So you need JVM to run Bazel anyways.

However, I think this is a legitimate request. We also need nojdk version because our CI machines already have a JDK. There is no need to download it again.

**Comment by tradergt** [comment]
Sorry, wasn't clear, yeah, I was going to install java on my ci/cd docker so Bazel has java but just don't need a version being downloaded for Bazel itself since we don't compile it and so forth. All of our developers have java already installed for other reasons so we also don't need it there.
