### ISSUE TITLE
Bazelisk version

### ISSUE THREAD

**Issue by miskin1991** [bazelbuild/bazelisk#314]
This shall be a quick one. I have done some digging in internet but I have not been able to find an answer. How can I know which bazelisk binary version I am using (not which bazel version is bazelisk using under the hood but the bazelisk release version that I have installed on my local machine and I run)?

If I run "/usr/local/bin/bazelisk --version" it returns the bazel version only.

**Comment by coeuvre** [comment]
`bazelisk version`

**Comment by miskin1991** [comment]
True, thank you @coeuvre , in fact it returns both bazelisk version and bazel version configured for the WORKSPACE. Very much appreciated.
