### ISSUE TITLE
Latest version was published to npm as 0.0.0-PLACEHOLDER

### ISSUE THREAD

**Issue by mattsoulanille** [bazelbuild/bazelisk#360]
The latest version of @bazel/bazelisk was [published to npm](https://www.npmjs.com/package/@bazel/bazelisk) as version `0.0.0-PLACEHOLDER`, the placeholder value in [package.json](https://github.com/bazelbuild/bazelisk/blob/master/package.json#L4).

**Comment by fweikert** [comment]
Fixed by https://github.com/bazelbuild/bazelisk/pull/491
