### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break Bazelisk in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/bazelisk#405]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking Bazelisk. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bd0f-4fb5-99ca-fbfd226744c7)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bd09-4810-b85b-db9abc31aac6)
- [Ubuntu 20.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bd0c-4b7e-ba97-d282155ea4b9)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-bd12-41d2-bc0b-1d7ab0a2ea6e)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by sgowroji** [comment]
Hi @bazelisk team, Could you please look into this issue. Thanks!

**Comment by philwo** [comment]
I’m not the right person to look into this anymore, but maybe @fweikert or @meteorcloudy can help?
