### ISSUE TITLE
Support arbitrary URL layouts

### ISSUE THREAD

**Issue by jmmv** [bazelbuild/bazelisk#423]
I'm in a situation where I have to download custom Bazel builds, but the only file hosting service I have access to imposes a weird URL layout on me. As a result, I cannot use `BAZELISK_BASE_URL` due to its assumptions on how the repository is laid out.

Could I suggest adding a new `BAZELISK_URL_FMT` variable or similar to generalize the way URLs are computed? It could take something like this:

```BAZELISK_URL_FMT=https://server.example.com/my/weird/<ARCH>/layout/bazel-<RELEASE>-foo/weirder/<OS>```

This new variable should conflict with at least `BAZELISK_BASE_URL` and result in an invalid configuration file error, because the two are incompatible.

Happy to take a stab at implementing this if the idea sounds reasonable.

**Comment by fweikert** [comment]
Hey Julio,
Great to see you again! The idea sounds good to me.

**Comment by jmmv** [comment]
Cool, cool. I actually wrote a patch that implements this last week but I'm clearing some hurdles before I can share it. Stay tuned!
