### ISSUE TITLE
Add ability to use custom JDK

### ISSUE THREAD

**Issue by JayBazuzi** [bazelbuild/bazelisk#430]
Our organization's security policies often prohibit the Java JDK that is included in Bazel due to some vulnerability.

To work around that we wrote a bootstrapper that downloads a newer, more acceptable JDK as well as the `-nojdk` variant of Bazel.

That seems like a job that Bazelisk could do for us, and would benefit all the other uses of Bazelisk as well.

**Comment by JayBazuzi** [comment]
Because our company policy requires downloading the JDK from an intranet-local cache, we'd need something like `BAZELISK_BASE_URL` but for the JDK. Perhaps `BAZELISK_JDK_BASE_URL`?

**Comment by JayBazuzi** [comment]
I see that bazelisk.py already has `BAZELISK_NOJDK`. Just porting that to bazelisk.go would be a step in the right direction.

**Comment by auzhva** [comment]
Hi,

Would someone please review that and possibly merge?

We need custom JDK to use system-level trust store with certificates, and currently we are using something like `startup --server_javabase=/usr/lib/jvm/java-11-openjdk-amd64` as a workaround.

This works fine, but we always have to download full versions and not to forget to setup this path every time for every user.

Would it be possible to review this PR and merge?
