### ISSUE TITLE
Flakiness downloading bazel (on windows)

### ISSUE THREAD

**Issue by phlax** [bazelbuild/bazelisk#432]
Our (Envoy) Windows CI seems to fail fairly frequently downloading the bazel bin:

```console
2023/03/03 08:56:37 Downloading https://releases.bazel.build/6.0.0/release/bazel-6.0.0-windows-x86_64.exe...
2023/03/03 08:56:51 could not download Bazel: HTTP GET https://releases.bazel.build/6.0.0/release/bazel-6.0.0-windows-x86_64.exe failed: Get "[https://releases.bazel.build/6.0.0/release/bazel-6.0.0-windows-x86_64.exe"](https://releases.bazel.build/6.0.0/release/bazel-6.0.0-windows-x86_64.exe%22): net/http: TLS handshake timeout
```

https://dev.azure.com/cncf/envoy/_build/results?buildId=129800&view=logs&j=b840a642-5ff3-5357-2e4b-e06e40b0cffd&t=67965174-5100-5631-9dc0-68b9f0aacb53&l=56

i didnt notice this happening in other jobs - so i believe this is specific to windows - but im not certain of this

either way, im wondering if it  would be possible to add some retry logic/config as i see discussed elsewhere

**Comment by alyssawilk** [comment]
https://dev.azure.com/cncf/envoy/_build/results?buildId=132015&view=results

https://dev.azure.com/cncf/envoy/_build/results?buildId=132024&view=results

**Comment by celestialorb** [comment]
Slapped together a rather rudimentary implementation in #495 as I've been encountering issues while downloading where a basic retry would likely have solved it.

**Comment by phlax** [comment]
cc @akshaysngupta

**Comment by akshaysngupta** [comment]
@celestialorb's PR looks reasonable to me. Can someone from maintainers review this?
