### ISSUE TITLE
Could Not Find the Systems GPU in This Case

### ISSUE THREAD

**Issue by NickDeBeenAIE** [bazelbuild/bazelisk#455]
<pre>python3 Remasterer.py
2023-05-03 20:16:08.427843: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-03 20:16:08.461663: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-05-03 20:16:08.461989: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-05-03 20:16:09.107163: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
</pre>

Yeah..... Bazelisk is not compatible with Ubuntu Jammy, or any Linux Distro for this matter.

This explains in short the amount of issues that this codes Linux users are elaborating about.

**Comment by NickDeBeenAIE** [comment]
By the way, my GT 1030's driver is version 530.

So it is not nor my installs of CuDNN either.

**Comment by meisterT** [comment]
@NickDeBeenAIE how is the python script that you are running related to bazelisk?

**Comment by meisterT** [comment]
Where is the `Remasterer.py` coming from? It's not from this repository, so I fail to see the connection with bazelisk.

**Comment by NickDeBeenAIE** [comment]
Its a program I partially made myself.

**Comment by meisterT** [comment]
Bazelisk is just a way to install/run Bazel and unrelated to GPU and your script.

**Comment by NickDeBeenAIE** [comment]
Ok, but it refuses to install completely.

I have had to re-install Linux.

I chose Ubuntu, which is just as bloated as Windows but lets be real here.

When I last tried to build Bazel with Bazelisk, I couldn't, because it fired error's my way.

**Comment by NickDeBeenAIE** [comment]
Wrong command, etc.

I.e., I have been given no instructions on how to get Bazelisk to install Bazel.

I like the "Keep It Simple Stupid" style of using something, so, if you could fire the correct command my way, that would be appropriate.

**Comment by meisterT** [comment]
what is the output of `bazelisk info`?

**Comment by fweikert** [comment]
> Wrong command, etc.
> 
> I.e., I have been given no instructions on how to get Bazelisk to install Bazel.
> 
> I like the "Keep It Simple Stupid" style of using something, so, if you could fire the correct command my way, that would be appropriate.

https://github.com/bazelbuild/bazelisk#installation

**Comment by NickDeBeenAIE** [comment]
I can't remember, but, I'll post.

**Comment by NickDeBeenAIE** [comment]
> > Wrong command, etc.
> > I.e., I have been given no instructions on how to get Bazelisk to install Bazel.
> > I like the "Keep It Simple Stupid" style of using something, so, if you could fire the correct command my way, that would be appropriate.
> 
> https://github.com/bazelbuild/bazelisk#installation

Permission denied.

I cannot write to this directory, even with ``sudo``.

**Comment by meisterT** [comment]
Which platform are you on, and which command did you run exactly?

**Comment by NickDeBeenAIE** [comment]
I installed Bazelisk-Bootstrap previously, then run this command:

``bazel install bazelisk``

That looks like a wrong command to me, because the usual wrong command error was given.

**Comment by fweikert** [comment]
To add to meisterT's comment: There are also instructions on how to install Bazel without Bazelisk at https://bazel.build/install

**Comment by NickDeBeenAIE** [comment]
And I'll re-open this issue with this:

<pre>sudo apt update &amp;&amp; sudo apt install bazel
Get:1 file:/var/cudnn-local-repo-ubuntu2204-8.9.0.131  InRelease [1,572 B]
Get:1 file:/var/cudnn-local-repo-ubuntu2204-8.9.0.131  InRelease [1,572 B]
Err:1 file:/var/cudnn-local-repo-ubuntu2204-8.9.0.131  InRelease
  The following signatures couldn&apos;t be verified because the public key is not available: NO_PUBKEY 8182C797D7522631
Hit:2 http://au.archive.ubuntu.com/ubuntu jammy InRelease                      
Hit:3 http://au.archive.ubuntu.com/ubuntu jammy-updates InRelease<font color="#A2734C">              </font>
Hit:4 http://au.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 https://storage.googleapis.com/bazel-apt stable InRelease                
Hit:6 https://dl.google.com/linux/chrome/deb stable InRelease                <font color="#A2734C">  </font>
Hit:7 http://security.ubuntu.com/ubuntu jammy-security InRelease<font color="#A2734C">             </font>
Reading package lists... Done<font color="#A2734C">                        </font>
<font color="#A2734C"><b>W: </b></font>GPG error: file:/var/cudnn-local-repo-ubuntu2204-8.9.0.131  InRelease: The following signatures couldn&apos;t be verified because the public key is not available: NO_PUBKEY 8182C797D7522631
<font color="#C01C28"><b>E: </b></font>The repository &apos;file:/var/cudnn-local-repo-ubuntu2204-8.9.0.131  InRelease&apos; is not signed.
<font color="#A2734C">N: </font>Updating from such a repository can&apos;t be done securely, and is therefore disabled by default.
<font color="#A2734C">N: </font>See apt-secure(8) manpage for repository creation and user configuration details.
</pre>

**Comment by meisterT** [comment]
This is unrelated to Bazelisk, please open an issue in https://github.com/bazelbuild/bazel instead. Also make sure you followed step 1 in https://bazel.build/install/ubuntu#install-on-ubuntu

**Comment by NickDeBeenAIE** [comment]
Well, Bazelisk won't install, nor run Bazel commands either.

Issue number 455 for more info.
