### ISSUE TITLE
Allow specify nojdk and non-release commit

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/bazelisk#469]
It looks like one cannot specify a non-release commit (e.g. `USE_BAZEL_VERSION=last_green`) as well as `BAZEL_NOJDK=1` to download a nojdk Bazel.

Instead, it will download a jdk Bazel (BAZEL_NOJDK is ignored).

This seems like a simple arg-parsing oversight. (FWIW, `BAZEL_NOJDK` isn't even documented, so perhaps its a mostly-untested feature?)

**Comment by tradergt** [comment]
For the java part, looks like there was a push to support NOJDK
https://github.com/bazelbuild/bazelisk/pull/531
It has not been released yet though

**Comment by fweikert** [comment]
I'll cut a new release
