### ISSUE TITLE
FR: Support WORKSPACE.bzlmod

### ISSUE THREAD

**Issue by satreix** [bazelbuild/bazelisk#484]
I part of migrating to bzlmod, I renamed my WORKSPACE file to WORKSPACE.bzlmod. It looks like bazelisk does not support this yet.

```console
$ mkdir new_project
$ cd new_project
$ touch WORKSPACE
$ echo '6.2.1' > .bazelversion
$ bazel --version
bazel 6.2.1

$ echo 'common --enable_bzlmod' >> .bazelrc
$ mv WORKSPACE WORKSPACE.bzlmod
$ bazel --version
bazel 6.3.0
```

IIUC the issue is in here: https://github.com/bazelbuild/bazelisk/blob/9943f1249b493d80333b19bf7132f7f7221ce174/bazelisk.py#L98-L101

**Comment by satreix** [comment]
Nevermind. As per https://docs.google.com/document/u/0/d/1JtXIVnXyFZ4bmbiBCr5gsTH4-opZAFf5DMMb-54kES0/mobilebasic?pli=1

> WORKSPACE.bzlmod does NOT replace the functionality of WORKSPACE for identifying the workspace root, therefore you still need the WORKSPACE file presented at your workspace root.

This feature is not required.

**Comment by brentleyjones** [comment]
It can as of 7.0 though, right?
