### ISSUE TITLE
Bazelisk tests are failing with Bazel@HEAD in Downstream

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/bazelisk#487]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3231#0189e25d-b910-49cc-b2e9-b33f012e3964

Platform : MacOS, Ubuntu, Windows

Logs :  
```
go_bazelisk_test FAILED
py3_bazelisk_test FAILED
py_bazelisk_test  FAILED
```
Steps:
```
git clone https://github.com/bazelbuild/bazelisk.git
git reset 9943f1249b493d80333b19bf7132f7f7221ce174 --hard
export USE_BAZEL_VERSION=428ba8c800ca756c00362bbc5dd69ab9237bcc4f
bazel test --flaky_test_attempts=3  test_output=streamed //...
```

CC Greenteam @comius

**Comment by comius** [comment]
cc @meteorcloudy 

Have there been changes to building for CentOS?

Bazelisks tries to use https://storage.googleapis.com/bazel-builds/artifacts/centos7/e89bb2e8da9278c7444b242d02f0ae382a760564/bazel
for Bazel last green. And the link is 404.

**Comment by comius** [comment]
This is also breaking CI: https://buildkite.com/bazel/bazel-bazel-examples/builds/1998#0189e3a2-f767-4ecd-ba5f-c0f0185030ff

**Comment by meteorcloudy** [comment]
Yes, there were five broken commits in https://buildkite.com/bazel-trusted/publish-bazel-binaries/builds?branch=master due to Windows arm64 build failure. I'll see if I can find a way to rebuild the missing binaries, but `last_green` should work again, reruning those job should fix them.
