### ISSUE TITLE
Issue Installing Bazel for MediaPipe on Raspberry Pi 4

### ISSUE THREAD

**Issue by itamarizen** [bazelbuild/bazelisk#493]
I've been trying to install Bazel for my Raspberry Pi 4 project in order to use MediaPipe. I've followed the instructions outlined in the readme.md at https://github.com/koenvervloesem/bazel-on-arm/tree/master. The initial steps seemed successful – "sudo make requirements" ran without any issues. However, I encountered an error when running "make bazel". The error message is as follows:

.
.
.
inflating: bazel/third_party/bazel_bootstrap/libunsafe-provider.jar
Building Bazel from scratch...
Building Bazel with Bazel.
DEBUG: /tmp/bazel_T5kgkfX6/out/external/bazel_toolchains/rules/rbe_repo/version_check.bzl:59:14:
Current running Bazel is not a release version and one was not defined explicitly in rbe_autoconfig target. Falling back to '3.1.0'
... (more debug messages)
ERROR: /tmp/bazel_T5kgkfX6/out/external/local_config_cc/BUILD:47:19: in cc_toolchain_suite rule @local_config_cc//:toolchain: cc_toolchain_suite '@local_config_cc//:toolchain' does not contain a toolchain for cpu 'arm'
ERROR: Analysis of target '//src:bazel_nojdk' failed; build aborted: Analysis of target '@local_config_cc//:toolchain' failed
INFO: Elapsed time: 34.781s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (55 packages loaded, 200 targets configured)
... (more info)
ERROR: Could not build Bazel
make: *** [Makefile:4: bazel] Error 1

For context, here is some information about my Raspberry Pi environment:
Raspbian Version: 11 (bullseye)
Kernel Version: 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux
I've tried researching this error and potential solutions, but I haven't been able to find a resolution. If you have any insights or suggestions on how I might be able to successfully install Bazel and proceed with using MediaPipe on my Raspberry Pi 4, I would greatly appreciate your assistance.

Thank you in advance for your time and support.

Best regards,

**Comment by fweikert** [comment]
Unrelated to Bazelisk - please file an issue in https://github.com/bazelbuild/bazel if the problem still exists
