### ISSUE TITLE
Server crashed during startup. while parsing option --digest_function=BLAKE3: Not a valid hash function

### ISSUE THREAD

**Issue by raphael10-collab** [bazelbuild/bazelisk#505]
root@k8s-eu-1-worker-3:~# go install github.com/bazelbuild/bazelisk@latest
    go: downloading github.com/bazelbuild/bazelisk v1.18.0
    go: downloading github.com/mitchellh/go-homedir v1.1.0
    go: downloading github.com/bgentry/go-netrc v0.0.0-20140422174119-9fd32a8b3d3d
    go: downloading github.com/hashicorp/go-version v1.6.0

    root@k8s-eu-1-worker-3:~/chromium-original/chromium/buildbuddy# bazelisk run -c opt server:buildbuddy
    Starting local Bazel server and connecting to it...
    INFO: Reading 'startup' options from /root/chromium-original/chromium/buildbuddy/.bazelrc: --digest_function=BLAKE3
    Server crashed during startup. Now printing /root/.cache/bazel/_bazel_root/02c189d792756a89af9527ccfdd2f927/server/jvm.out
    While parsing option --digest_function=BLAKE3: Not a valid hash function.
    root@k8s-eu-1-worker-3:~/chromium-original/chromium/buildbuddy# 
    
    root@k8s-eu-1-worker-3:~# cat /root/.cache/bazel/_bazel_root/02c189d792756a89af9527ccfdd2f927/server/jvm.out
    While parsing option --digest_function=BLAKE3: Not a valid hash function.

OS: Ubuntu 22.04
go version : go1.21.1 linux/amd64

How to make it work?

**Comment by brentleyjones** [comment]
That flag only works on 6.4.0+ (currently in RC).

Your bug report doesn't seem to be an issue with Bazelisk though. Can you file an issue with the project that you are trying to build?

**Comment by raphael10-collab** [comment]
Hi @brentleyjones ! 

I close the issue, since I decided to use other tools instead of `buildbuddy` , which may cause the issue
