### ISSUE TITLE
Bazelisk 1.18 doesn't handle WORKSPACE-less repositories

### ISSUE THREAD

**Issue by katre** [bazelbuild/bazelisk#514]
I spent a while this weekend trying to figure out why a new project, which had a `MODULE.bazel` file (and a `WORKSPACE.bzlmod`), but no `WORKSPACE` file, was having the `.bazelversion` file ignored.

After some debugging I realized that bazelisk 1.18.0 only looks for `.bazelversion` in the repository root, and identifies the repository root by the presence of a `WORKSPACE` file.

Looks like this was fixed in b7f5c7570df35ce2273afa0c15f4bc5038fb126a, but we should cut a new Bazelisk release with that commit before Bazel 7.0 is released.

**Comment by brentleyjones** [comment]
@fweikert can we get a new release? 🙏

**Comment by crncnnr** [comment]
I would also appreciate a new release, please!

**Comment by fweikert** [comment]
https://github.com/bazelbuild/bazelisk/releases/tag/v1.19.0
