### ISSUE TITLE
Bazelisk does not print its version anymore in `1.18.0` when calling `bazelisk version`

### ISSUE THREAD

**Issue by sitaktif** [bazelbuild/bazelisk#516]
Bazelisk used to have a line containing `Bazelisk version: ...`.

Bazelisk `1.17.0`:

```
% bazelisk version
Bazelisk version: development
Build label: [...]
Build target: [...]
Build time: [...]
Build timestamp: [...]
Build timestamp as int: [...]
```

Bazelisk `1.18.0`:

```
% bazelisk version
Build label: [...]
Build target: [...]
Build time: [...]
Build timestamp: [...]
Build timestamp as int: [...]
```

I would expect the line to still be present in `1.18.0`, ideally with the correct version number. Alternatively, I would expect bazelisk to provide and alternate way to get its version.

**Comment by AleksandrLiadov** [comment]
Same issue
