### ISSUE TITLE
could not download Bazel when I want to execute the command：bazel build onos

### ISSUE THREAD

**Issue by IBBLdeSS** [bazelbuild/bazelisk#555]
1. Ubuntu 20.04 (LTS) uses OpenJDK 11 
2. Install Bazelisk：
wget https://github.com/bazelbuild/bazelisk/releases/download/v1.18.0/bazelisk-linux-amd64
chmod +x bazelisk-linux-amd64
sudo mv bazelisk-linux-amd64 /usr/local/bin/bazel
bazel version
3. Build ONOS from source:
# from Gerrit
git clone https://gerrit.onosproject.org/onos
4. cd onos
bazel build onos
Then got error:
bs@bs-virtual-machine:~/onos/onos$ bazel build onos
2024/02/13 22:00:24 Downloading https://releases.bazel.build/6.0.0-pre.20220421.3/release/bazel-6.0.0-pre.20220421.3-linux-x86_64...
2024/02/13 22:00:25 could not download Bazel: HTTP GET https://releases.bazel.build/6.0.0-pre.20220421.3/release/bazel-6.0.0-pre.20220421.3-linux-x86_64 failed with error 404

**Comment by IBBLdeSS** [comment]
It looks like it's a problem with the URL  https://releases.bazel.build/6.0.0-pre.20220421.3/release/bazel-6.0.0-pre.20220421.3-linux-x86_64..., the web page has no content， but I don't know how to fix it

**Comment by meteorcloudy** [comment]
The correct URL is `https://releases.bazel.build/6.0.0/rolling/6.0.0-pre.20220421.3/bazel-6.0.0-pre.20220421.3-linux-x86_64`

**Comment by meteorcloudy** [comment]
@IBBLdeSS How are you specifying the bazel version? In `.bazelversion` file? Can you share the content?

**Comment by IBBLdeSS** [comment]
Now I don't know how to specify the bazel version，because now there is no .bazelversion file in both gerri and github downloads of onos, and it looaks like a lot of files are missing compared to the previous downloads
<img width="437" alt="388f9d67ce9c3247c11824147192fae" src="https://github.com/bazelbuild/bazelisk/assets/120639091/2fd61fcb-e7b6-4b33-aab7-1c2f0c6c595b">
![1707875361604](https://github.com/bazelbuild/bazelisk/assets/120639091/91136ce4-1589-4872-ac73-aa6e1b46e597)

**Comment by IBBLdeSS** [comment]
Now I don't know how to specify the bazel version，because there is no .bazelversion file in both gerri and github downloads of onos, and it looks like a lot of files are missing compared to the previous downloads：

<img width="437" alt="388f9d67ce9c3247c11824147192fae" src="https://github.com/bazelbuild/bazelisk/assets/120639091/fdcae9a5-cbbb-4ab5-ba76-3ed0c0ebacb7">

![1707875361604](https://github.com/bazelbuild/bazelisk/assets/120639091/8d09e48e-f58b-4c47-b922-6413798e7eec)

**Comment by IBBLdeSS** [comment]
> The correct URL is `https://releases.bazel.build/6.0.0/rolling/6.0.0-pre.20220421.3/bazel-6.0.0-pre.20220421.3-linux-x86_64`

Oh ,yes ,but I don't know how to change the URL

**Comment by IBBLdeSS** [comment]
Now I don't know how to specify the bazel version，because there is no .bazelversion file in both gerri and github downloads of onos, and it looks like a lot of files are missing compared to the previous downloads. This is the difference between the current and previous downloads:
<img width="437" alt="388f9d67ce9c3247c11824147192fae" src="https://github.com/bazelbuild/bazelisk/assets/120639091/103683ba-4714-40c1-8054-8407bdd7767c">

![1707875361604](https://github.com/bazelbuild/bazelisk/assets/120639091/78a03aa1-e858-4841-990e-d3d608173274)


> @IBBLdeSS How are you specifying the bazel version? In `.bazelversion` file? Can you share the content?

**Comment by IBBLdeSS** [comment]
> @IBBLdeSS How are you specifying the bazel version? In `.bazelversion` file? Can you share the content?
The content of the previous .bazelversion file was:
<img width="215" alt="1707876377121" src="https://github.com/bazelbuild/bazelisk/assets/120639091/65b2c2ff-284f-4758-bfe1-4cacd69501c3">

**Comment by IBBLdeSS** [comment]
The content of the previous  `.bazelversion` file was:  
<img width="216" alt="1707879620236" src="https://github.com/bazelbuild/bazelisk/assets/120639091/78146091-27a5-4c63-a4d5-865214ffe5a6">


> @IBBLdeSS How are you specifying the bazel version? In `.bazelversion` file? Can you share the content?

**Comment by meteorcloudy** [comment]
I couldn't reproduce this, do you have any other Bazelisk related environment variable set?

**Comment by IBBLdeSS** [comment]
Thanks for the tip, I manually downloaded bazel-6.0.0-pre.20220421.3-linux-x86_64 and put it in the specified folder：home/.cache/bazelisk/bin/bazelbuild,  resolved the URL error，but I got  new errors:

Extracting Bazel installation...
Starting local Bazel server and connecting to it...
INFO: Repository npm instantiated at:
  /home/ss/onos/onos/WORKSPACE:173:13: in <toplevel>
  /home/ss/.cache/bazel/_bazel_ss/6eb2507d8948b213aba0a0b56069db8a/external/build_bazel_rules_nodejs/index.bzl:89:18: in yarn_install
Repository rule yarn_install defined at:
  /home/ss/.cache/bazel/_bazel_ss/6eb2507d8948b213aba0a0b56069db8a/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl:424:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'npm':
   Traceback (most recent call last):
	File "/home/ss/.cache/bazel/_bazel_ss/6eb2507d8948b213aba0a0b56069db8a/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 417, column 13, in _yarn_install_impl
		fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed: yarn install v1.19.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "/home/ss/onos/onos/web/gui2/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (error An unexpected error occurred: "https://registry.yarnpkg.com/@angular/core/-/core-10.2.4.tgz: connect ECONNREFUSED 104.16.27.34:443".
)
ERROR: /home/ss/onos/onos/WORKSPACE:173:13: fetching yarn_install rule //external:npm: Traceback (most recent call last):
	File "/home/ss/.cache/bazel/_bazel_ss/6eb2507d8948b213aba0a0b56069db8a/external/build_bazel_rules_nodejs/internal/npm_install/npm_install.bzl", line 417, column 13, in _yarn_install_impl
		fail("yarn_install failed: %s (%s)" % (result.stdout, result.stderr))
Error in fail: yarn_install failed: yarn install v1.19.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "/home/ss/onos/onos/web/gui2/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (error An unexpected error occurred: "https://registry.yarnpkg.com/@angular/core/-/core-10.2.4.tgz: connect ECONNREFUSED 104.16.27.34:443".
)
ERROR: no such package '@npm//@bazel/protractor': yarn_install failed: yarn install v1.19.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "/home/ss/onos/onos/web/gui2/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
 (error An unexpected error occurred: "https://registry.yarnpkg.com/@angular/core/-/core-10.2.4.tgz: connect ECONNREFUSED 104.16.27.34:443".
)
INFO: Elapsed time: 34.441s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)


> I couldn't reproduce this, do you have any other Bazelisk related environment variable set?

**Comment by IBBLdeSS** [comment]
Now facing thess problems：

$ bazel build onos
WARNING: Download from https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.19.8/rules_go-v0.19.8.tar.gz failed: class java.net.ConnectException Connection refused (Connection refused)
WARNING: Download from https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/0.18.1/bazel-gazelle-0.18.1.tar.gz failed: class java.net.ConnectException Connection refused (Connection refused)
INFO: Analyzed target //:onos (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/ss/onos/onos/web/gui/BUILD:98:8: Executing genrule //web/gui:_onos-gui-npm-install failed: (Exit 1): bash failed: error executing command (from target //web/gui:_onos-gui-npm-install) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Target //:onos failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/ss/onos/onos/web/gui/BUILD:241:8 Executing genrule //web/gui:onos-web-gui failed: (Exit 1): bash failed: error executing command (from target //web/gui:_onos-gui-npm-install) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 511.988s, Critical Path: 511.45s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

**Comment by IBBLdeSS** [comment]
Now facing these problems：

$ bazel build onos
WARNING: Download from https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.19.8/rules_go-v0.19.8.tar.gz failed: class java.net.ConnectException Connection refused (Connection refused)
WARNING: Download from https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/0.18.1/bazel-gazelle-0.18.1.tar.gz failed: class java.net.ConnectException Connection refused (Connection refused)
INFO: Analyzed target //:onos (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: /home/ss/onos/onos/web/gui/BUILD:98:8: Executing genrule //web/gui:_onos-gui-npm-install failed: (Exit 1): bash failed: error executing command (from target //web/gui:_onos-gui-npm-install) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox
Target //:onos failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/ss/onos/onos/web/gui/BUILD:241:8 Executing genrule //web/gui:onos-web-gui failed: (Exit 1): bash failed: error executing command (from target //web/gui:_onos-gui-npm-install) /bin/bash -c ... (remaining 1 argument skipped)

Use --sandbox_debug to see verbose messages from the sandbox
INFO: Elapsed time: 511.988s, Critical Path: 511.45s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully

**Comment by fweikert** [comment]
Why are you using this specific Bazel version? It's a prerelease version for Bazel 6.0, which doesn't really make sense to use nowadays.

Your options:

- If you want to use LTS track 6 for compatibility reasons, you should use the latest stable version [6.5](https://github.com/bazelbuild/bazel/releases/tag/6.5.0)
- If you want the latest stable release you should go with [7.0.2](https://github.com/bazelbuild/bazel/releases/tag/7.0.2)
- If you want to use a rolling release, you should use one of the current [8.x](https://bazel.build/release/rolling) ones.

The failures you mentioned in the last comment are unrelated to Bazelisk - Bazel cannot download some external dependencies, maybe due to a firewall or some other network settings.

**Comment by heliosgo** [comment]
> Now facing these problems：
> 
> $ bazel build onos WARNING: Download from https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/rules_go/releases/download/v0.19.8/rules_go-v0.19.8.tar.gz failed: class java.net.ConnectException Connection refused (Connection refused) WARNING: Download from https://storage.googleapis.com/bazel-mirror/github.com/bazelbuild/bazel-gazelle/releases/download/0.18.1/bazel-gazelle-0.18.1.tar.gz failed: class java.net.ConnectException Connection refused (Connection refused) INFO: Analyzed target //:onos (0 packages loaded, 0 targets configured). INFO: Found 1 target... ERROR: /home/ss/onos/onos/web/gui/BUILD:98:8: Executing genrule //web/gui:_onos-gui-npm-install failed: (Exit 1): bash failed: error executing command (from target //web/gui:_onos-gui-npm-install) /bin/bash -c ... (remaining 1 argument skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox Target //:onos failed to build Use --verbose_failures to see the command lines of failed build steps. ERROR: /home/ss/onos/onos/web/gui/BUILD:241:8 Executing genrule //web/gui:onos-web-gui failed: (Exit 1): bash failed: error executing command (from target //web/gui:_onos-gui-npm-install) /bin/bash -c ... (remaining 1 argument skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox INFO: Elapsed time: 511.988s, Critical Path: 511.45s INFO: 2 processes: 2 internal. FAILED: Build did NOT complete successfully

@IBBLdeSS I've got same error. Did you finally solve it?
