### ISSUE TITLE
Bazelisk pulls incorrect Bazel on Windows ARM64

### ISSUE THREAD

**Issue by jxy-s** [bazelbuild/bazelisk#572]
The x64 version of bazelisk is compatible with a Windows ARM64 machine, it will run under x64 emulation on Windows. However it ends up pulling the x64 version of Bazel which causes unintended downstream behavior.
- toolchains are not resolved as expected
- the host OS is not reflected correctly causing the default compilation to produce an x64 binary instead of an ARM64 one

Bazelisk should pull the ARM64 version of when running on Windows ARM64 instead of the x64 version.

See: https://github.com/bazelbuild/bazel/issues/22164#issuecomment-2081383179

**Comment by meteorcloudy** [comment]
Maybe it's as simple as adding another target for windows arm64 here?
https://github.com/bazelbuild/bazelisk/blob/47f60477721681a117cbf905784ee5220100e68b/BUILD#L145-L153

**Comment by albertocavalcante** [comment]
@meteorcloudy my understanding is the same. I will try to submit a PR for this.
