### ISSUE TITLE
Support `Tools/` in case-sensitive file systems

### ISSUE THREAD

**Issue by luispadron** [bazelbuild/bazelisk#577]
We've been keeping our wrapper in a uppercased `Tools/` directory at `Tools/bazel`. This is because we have existing stuff in `Tools/`. This works fine for case-insensitive file systems but fails silently on a case-sensitive file system as bazelisk only checks for `tools/bazel`.

Could we support both/or any casing here?

**Comment by keith** [comment]
maybe best solved by https://github.com/bazelbuild/bazelisk/pull/567

**Comment by luispadron** [comment]
yes that would be perfect thank you @keith. Any idea if theres a desire to merge that from the maintainers? We can keep this open and close it if that merges

**Comment by keith** [comment]
haven't heard anything
