### ISSUE TITLE
Bazelisk unable to set variable "-Dcom.sun.net.ssl.checkRevocation=false"

### ISSUE THREAD

**Issue by Ryan-Boustany** [bazelbuild/bazelisk#623]
For context I am trying to follow this older `Updating to a new version of libphonenumber` instructions here I need this for my project: https://github.com/Ryan-Boustany/intl-tel-input/blob/v17.0.21/.github/CONTRIBUTING.md. 

I am trying to bypass ssl verification whilst running the build.

Command I need to run: `bazelisk build :all`

Error I am facing: `PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target`

My question is either how can i get around this issue or how can I set that variable to allow me to bypass the ssl verification checks.

**Comment by Ryan-Boustany** [comment]
Here is a more detailed output of the error when running the comamnd
```
WARNING: Download from https://github.com/bazelbuild/rules_java/releases/download/5.4.1/rules_java-5.4.1.tar.gz failed: class javax.net.ssl.SSLHandshakeException PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
ERROR: An error occurred during the fetch of repository 'rules_java':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/bazel_tools/tools/build_defs/repo/http.bzl", line 125, column 45, in _http_archive_impl
                download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/bazelbuild/rules_java/releases/download/5.4.1/rules_java-5.4.1.tar.gz] to /private/var/tmp/_bazel_boustry/287eb8ada5cb1ef597fcf96f64786701/external/rules_java/temp47235204782365388/rules_java-5.4.1.tar.gz: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```

**Comment by fweikert** [comment]
Unfortunately I cannot really help you here since this is not a Bazelisk issue. These two links seem to have some solutions for your problem: 

https://github.com/tensorflow/tensorflow/issues/62894
https://github.com/bazelbuild/bazel/issues/3915
