### ISSUE TITLE
bazelisk sometimes fails to download Bazel binaries

### ISSUE THREAD

**Issue by werkt** [bazelbuild/bazelisk#626]
The ubuntu22 image (and probably others) have a bazelisk that precedes a number of fixes in golang with http fetches, notably identified in https://github.com/googleapis/google-cloud-go/issues/7440

```
2024/10/09 13:25:45 could not download Bazel: failed to download bazel: failed to download bazel: could not copy from https://releases.bazel.build/7.3.2/release/bazel-7.3.2-linux-x86_64 to /var/lib/buildkite-agent/.cache/bazelisk/downloads/_tmp/download1376248149: stream error: stream ID 1; INTERNAL_ERROR; received from peer
```
is the reported error, and I expect that with a newer bazelisk (current on image is 1.19, likely running against older golangs) like 1.22 with golang 1.23 basis, this situation should be improved.

**Comment by meteorcloudy** [comment]
This is still happening on Bazel CI: see failed jobs in https://buildkite.com/bazel/bcr-presubmit/builds/8565#0192e691-f5e4-43fd-afda-c2b24fe85137
