### ISSUE TITLE
Bazelisk 1.24 downloads over and over again

### ISSUE THREAD

**Issue by visglz** [bazelbuild/bazelisk#640]
Hi,

I just updated to bazelisk 1.24. When no specific version is defined it downloads the latest version over and over again with every invocation.

It can be reproduced the following way under Linux (note, that there is no USE_BAZEL_VERSION in ~/.bazeliskrc:

```shell
# Downloads 7.4.1 on every invocation even if present in `/.cache/bazelisk`
./bazelisk-1.24 --version
./bazelisk-1.24 --version
# No download happens
./bazelisk-1.23 --version
USE_BAZEL_VERSION=7.x ./bazelisk-1.24 --version
```

There is a significant delay when no version is provided with 1.24. When running it via strace one can see quite some amount of network traffic.

Could it be that #636 introduced this behaviour?

**Comment by meteorcloudy** [comment]
I also noticed the same issue, @fweikert
