### ISSUE TITLE
404 on v0.0.6 Release

### ISSUE THREAD

**Issue by promiseofcake** [bazelbuild/bazelisk#68]
Seeing a 404 for binary assets as part of the v0.0.6 release.

https://github.com/bazelbuild/bazelisk/releases/download/v0.0.6/bazelisk-darwin-amd64

**Comment by philwo** [comment]
I had to remove v0.0.6 and rerelease this version as v0.0.7, because I missed a commit for v0.0.6. Sorry! 😊

**Comment by promiseofcake** [comment]
Thanks!
