### ISSUE TITLE
"go get" command in README.md fails in module mode

### ISSUE THREAD

**Issue by chases2** [bazelbuild/bazelisk#70]
Issue:
The "go get" command in README.md doesn't function when go.mod is parsed
`go get github.com/bazelbuild/bazelisk`
This effect was recreated with three out of four users trying to install bazelisk, so it's somewhat flaky.

Behavior:
```
$ go get github.com/bazelbuild/bazelisk
go: github.com/bazelbuild/bazelisk@v0.0.7: parsing go.mod: unexpected module path "github.com/philwo/bazelisk"
go: error loading module requirements
```

Possible Cause:
I believe that the [go.mod](https://github.com/bazelbuild/bazelisk/blob/c2912d89cfa24e3d463e3be5e63c15f0e68923d5/go.mod#L1) file is referencing the wrong repository

**Comment by philwo** [comment]
Thank you for the report! Yes, I forgot to update the URLs in the `go.mod` and `BUILD` after the repository was migrated to the bazelbuild repository. I'll send a fix in a minute.

**Comment by philwo** [comment]
@chases2 I've created a new release v0.0.8 with the fix included. Could you let me know if it works for you now?

**Comment by chases2** [comment]
The command works on my machine, downloading the development version (apparently). Thanks!

```
$ bazelisk version
Bazelisk version: development
Build label: 0.27.0
...
```
