### ISSUE TITLE
Support for Installing Custom Bazel Versions 

### ISSUE THREAD

**Issue by borkaehw** [bazelbuild/bazelisk#79]
We use a fork for Bazel at Lucid Software because we utilize features in Bazel that are still in code review or are too premature for a pull request to the main Bazel repo. 

We would like to be able to use Bazelisk with our fork of the Bazel repo, so we can manage Bazel upgrades while on a custom version of Bazel.

Currently Bazelisk only supports downloading official releases.
```
fmt.Sprintf("https://releases.bazel.build/%s/%s/%s", version, kind, filename)
```

It would be nice to have an option to choose between the normal GitHub release URL like

```
fmt.Sprintf("https://github.com/%s/bazel/releases/download/%s/%s", remote, version, filename)
```

We already have a prototype. We are happy to draft a PR or draft a design document. Thanks for your consideration.

**Comment by philwo** [comment]
Hi @borkaehw,

this is a feature I wanted to add anyway - feel free to send a PR (with accompanying documentation change for the README on how to use it) and we can get it in. :)

Thanks!

**Comment by borkaehw** [comment]
Thanks for your support. Currently I am thinking of something as simple as a `--remote` flag. If the flag is provided like `--remote=the-fork`, it would use the URL `https://github.com/the-fork/bazel/releases/download/...`, otherwise use the original one. It still restricts the use cases to official releases and GitHub releases, but I suppose it would cover most of the cases.

What do you think?
