### ISSUE TITLE
Feature request: resolve latest version of Bazel from something other than GitHub's APIs

### ISSUE THREAD

**Issue by j3parker** [bazelbuild/bazelisk#87]
In #18 it was mentioned that Bazelisk can fail because GitHub will rate limit IPs, which can be a problem on shared networks.

```json
{
    "message": "API rate limit exceeded for 64.235.99.100. (But here's the good news: Authenticated 
    requests get a higher rate limit. Check out the documentation for more details.)",
    "documentation_url": "https://developer.github.com/v3/#rate-limiting"
}
```

We hit this in our office because we generate our `WORKSPACE` in our non-Bazel build (as we migrate) and sometimes users do a clean build which deletes this file. Bazelisk will only use `.bazelrc` if it's beside a `WORKSPACE` file.

Our fix is to generate our Bazel build before invoking Bazel, which is totally reasonable/the right thing for us. It would still probably be good for Bazelisk to use non-GitHub infrastructure for resolving the latest version, as mentioned in #18 (it would have hidden our bug, which would suck for us, but it seems like the right thing for Bazelisk).

**Comment by philwo** [comment]
@fweikert Can we reuse your logic that gets the latest RC from GCS also for this case?

@j3parker Sorry for the trouble! We'll fix this. :) It looks like you found a solution for your use case for now, but in case you need another workaround - if you have an API token, you could set the `BAZELISK_GITHUB_TOKEN` environment variable, and Bazelisk should use it to query the API.

**Comment by j3parker** [comment]
Ah it's no trouble for us. The loud failure was helpful :) If this issue were already implemented we would have potentially silently downloaded a more up to date version of Bazel than we needed. So I think we were doing things wrong. 

The token thing is nice, thanks! I think we won't need it but I'll keep it in mind.

**Comment by Yannic** [comment]
Would it be sufficient to write a cronjob/cloud function that mirrors the JSON file on GCS once a day or so, and point bazelisk to the GCS URL by default?

**Comment by j3parker** [comment]
Another motivation for this is that GitHub hasn't been the most stable. Perhaps GCS with a GitHub fallback could be awesome?

**Comment by fweikert** [comment]
@Yannic : it should be possible to retrieve the latest version from the GCS bucket layout, which means we don't need an additional json file.

GitHub has been a single point of failure in the past. Even if we fix the version resolution we should have a look at "bazelisk --migrate" which currently requires GitHub, too.

**Comment by keith** [comment]
From our experience, even with the recent GitHub downtime, mirror.bazel.build is consistently worse than GitHub, we get many download failures from it per day, where as with GitHub we only ever get them during known downtime

**Comment by j3parker** [comment]
One possibility is to prefer one, but use the other as a fallback. More complicated, but more robust.

**Comment by fweikert** [comment]
@keith : What exact error do you get? If there's a problem with the mirror we should fix it.

**Comment by keith** [comment]
```
WARNING: Download from https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz failed: class com.google.devtools.build.lib.bazel.repository.downloader.UnrecoverableHttpException Checksum was faf80bb9a40c6fb6c14cba12b5727bbe6c817bc0e7bc4f6991428250754a803b but wanted 232b1c3511f0d26e92582b7c3cc363be7ac633e371854ca2f2e9f2b50eb72a75
ERROR: An error occurred during the fetch of repository 'remotejdk11_linux':
   java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz] to /root/.cache/bazel/_bazel_root/69693e54603dc2f7d82afd5028699a20/external/remotejdk11_linux/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz: Checksum was faf80bb9a40c6fb6c14cba12b5727bbe6c817bc0e7bc4f6991428250754a803b but wanted 232b1c3511f0d26e92582b7c3cc363be7ac633e371854ca2f2e9f2b50eb72a75
ERROR: /root/.cache/bazel/_bazel_root/69693e54603dc2f7d82afd5028699a20/external/bazel_tools/tools/jdk/BUILD:494:1: @bazel_tools//tools/jdk:remote_jdk11 depends on @remotejdk11_linux//:jdk in repository @remotejdk11_linux which failed to fetch. no such package '@remotejdk11_linux//': java.io.IOException: Error downloading [https://mirror.bazel.build/openjdk/azul-zulu11.2.3-jdk11.0.1/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz] to /root/.cache/bazel/_bazel_root/69693e54603dc2f7d82afd5028699a20/external/remotejdk11_linux/zulu11.2.3-jdk11.0.1-linux_x64.tar.gz: Checksum was faf80bb9a40c6fb6c14cba12b5727bbe6c817bc0e7bc4f6991428250754a803b but wanted 232b1c3511f0d26e92582b7c3cc363be7ac633e371854ca2f2e9f2b50eb72a75
```

We see many errors along these lines
