### ISSUE TITLE
Create bazelisk --bisect

### ISSUE THREAD

**Issue by Yannic** [bazelbuild/bazelisk#92]
It would be awesome if bazelisk had an option to bisect build failures locally, like it's proposed in the `Ideas for the future` section of the readme.

As a starting point, we could limit it to `last_green` versions of Bazel where we already have a compiled binary. That should hopefully narrow it down to a sufficiently small range of commits so see the culprint.

**Comment by jin** [comment]
See https://github.com/bazelbuild/bazel/blob/master/scripts/bazel-bisect.sh, but instead of building from source we can now pull the prebuilt binary.

**Comment by meteorcloudy** [comment]
This is implemented now: https://github.com/bazelbuild/bazelisk#--bisect
